@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json

### 로컬 로그인

POST {{host}}/login HTTP/1.1
content-type: {{contentType}}

{
  "userId": "testsdsds1212",
  "password": "12345678aaa@",
  "resourceServer": "local"
}

### 깃허브 로그인

GET {{host}}/login/github HTTP/1.1
content-type: {{contentType}}

### 회원가입

POST {{host}}/signup HTTP/1.1
content-type: {{contentType}}

{
  "userId": "test123",
  "password": "123456a@",
  "nickname": "test"
}

###

POST {{host}}/signup/check-id HTTP/1.1
content-type: {{contentType}}

{
  "userId": "test"
}

### 앱전용 깃허브로그인

@appToken=
GET https://api.github.com/user
content-type: {{contentType}}
Authorization: bearer {{appToken}}
