@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json

###

# @name login
POST {{host}}/login HTTP/1.1
content-type: {{contentType}}

{
  "userId": "test123",
  "password": "123456a@",
  "resourceServer": "local"
}

### 기록 받아오기

@authToken = {{login.response.body.token}}

### 특정 이슈 하나 불러오기

# @issueId=11

GET {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 이슈 불러오기

GET {{host}}/issue
?page=4
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 이슈 생성 (1). 관계 테이블이 없는 경우*

POST {{host}}/issue HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "이슈 타이틀",
  "content": null,
  "author": "이슈 작성자",
  "label": null,
  "mid": null,
  "assignees": null
}

### 이슈 생성 (2). 관계 테이블이 있는 경우

POST {{host}}/issue HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "testtesttest",
  "content": null,
  "author": "이슈 작성자",
  "labels": [
    {
      "name": "baseball"
    },
    {
      "name": "soccer"
    }
  ],
  "mid": null,
  "assignees": null
}

### 이슈 수정(1). 기본 내용 수정

@issueId=47

PATCH {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "content": "바뀔 내용",
  "isOpen": false,
  "title": "바뀔 타이틀"
}

# ### 이슈 수정(2). 이슈에 할당되어 있는 label 수정

PATCH {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "labels": [
    {
      "name": "question",
      "state": false
    },
    {
      "name": "bug",
      "state": true
    }
  ]
}

# ### 이슈 수정(3). 이슈에 할당되어 있는 assginee 추가

PATCH {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "assignees": [
    {
      "uid": 6,
      "state": true
    },
    {
      "uid": 8,
      "state": true
    }
  ]
}

# ### 이슈 수정(4). 이슈에 할당되어 있는 assginee 삭제

PATCH {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "assignees": [
    {
      "uid": 6,
      "state": false
    },
    {
      "uid": 8,
      "state": false
    }
  ]
}

### 이슈 수정 (5). assignees 추가/삭제 동시에 테스트

PATCH {{host}}/issue/{{issueId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "assignees": [
    {
      "uid": 6,
      "state": false
    },
    {
      "uid": 8,
      "state": false
    },
    {
      "uid": 10,
      "state": true
    }
  ]
}
