@hostname = localhost
@port = 5000
@develop = http://{{hostname}}:{{port}}/api
@server = http://group05issuetracker.duckdns.org:49203/api
@host = {{develop}}
@contentType = application/json

### 로컬 로그인

# @name login
POST {{host}}/login HTTP/1.1
content-type: {{contentType}}

{
  "userId": "testId1",
  "password": "123456a@",
  "resourceServer": "local"
}
### 기록 받아오기

@authToken = {{login.response.body.token}}

### 마일스톤 불러오기

GET {{host}}/milestone/ HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 마일스톤 추가하기

POST {{host}}/milestone/ HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "[백엔드] 로그인 화면 구성",
  "content": "로그인 API 구성"
}

###

POST {{host}}/milestone/ HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "[iOS] 로그인 화면 구성",
  "dueDate": "2020-12-12"
}

###

POST {{host}}/milestone/ HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "[FE] 타이틀 화면 구성",
  "content": "메인화면을 구성합니다.",
  "dueDate": "2020-10-30"
}

### 마일스톤 삭제하기 (데이터 베이스 확인후 설정)

@deleteId=

DELETE {{host}}/milestone/{{deleteId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 마일스톤 수정하기

@editId=3

PATCH {{host}}/milestone/{{editId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "수정 되었다!",
  "content": "진짜 해치웠나?"
}

###

PATCH {{host}}/milestone/{{editId}} HTTP/1.1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "isOpen": false
}